spring:
   datasource:
      url: jdbc:mysql://localhost:3306/ljw?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: luo520
      driver-class-name: com.mysql.jdbc.Driver
   redis:
      database: 2   # Redis数据库索引（默认为0）
      host: 47.107.55.207  # Redis服务器地址
      port: 6379         # Redis服务器连接端口
      password: luo520   # Redis服务器连接密码（默认为空）
      max-wait: 30000    # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-active: 100   # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 20     # 连接池中的最大空闲连接
      min-idle: 0     # 连接池中的最小空闲连接
      timeout: 5000  # 连接超时时间（毫秒）
#mybatis:
  #mapper-locations: classpath*:mapper/*.xml